name: Build

on:
  push:
    branches:
      - main
    tags:        
      - v*
  pull_request:
    branches:    
      - main

jobs:
  build-linux-windows:
    name: Build Linux/Windows
    runs-on: ubuntu-latest      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run build with docker
        uses: addnab/docker-run-action@v3
        with:
          image: electronuserland/builder:wine
          options: -v ${{ github.workspace }}:/project
          run: |
              cd /project
              npm install
              npm run dist:wl
      - name: Upload Artifacts
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v3
        with:
          name: win-lin-bin
          path: |
            ./dist/*.exe
            ./dist/*.blockmap
            ./dist/*.AppImage
            ./dist/*.deb
            ./dist/*.snap

  build-mac:
    name: Build Mac
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Run build
        run: npm run dist:mac
      - name: Upload Artifacts
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v3
        with:
          name: mac-bin
          path: |
            ./dist/*.blockmap
            ./dist/*.deb
            ./dist/*.zip
  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/v')
    needs:  [build-linux-windows, build-mac]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./win-lin-bin/*.exe
            ./win-lin-bin/*.blockmap
            ./win-lin-bin/*.AppImage
            ./win-lin-bin/*.deb
            ./win-lin-bin/*.snap
            ./mac-bin/*.dmg
            ./mac-bin/*.zip
            ./mac-bin/*.blockmap