name: Build

on:
  push

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - name: directory
        run: ls
      - name: project directory
        run: ls /project
      - name: node version
        run: node -v
